config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
     member do
       post :start
     end
   end

  resources :test_passages, only: %i[show update] do
    member do

      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/admin.rb
class Admin < User
  
  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_numbers_of_answers

  scope :right_answers, -> { where(correct: true) }

  private

  def validate_numbers_of_answers
    errors.add(:answers, "too much") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :questions
  
  has_many :test_passages
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy_tests, -> { where(level: 0..1) }
  scope :medium_tests, -> { where(level: 2..4) }
  scope :hard_tests, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, ->(category) { joins(:category).where(categories: { title: category }) }

  def self.tests_by_category(category)
    by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question


  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def question_number
    test.questions.ids.sort.index(current_question.id) + 1
  end

  def rate
    correct_questions / test.questions.count.to_f * 100
  end

  def passed?
    rate >= PASS_RATE
  end
   
  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    if answer_ids.present?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end    
  end

  def correct_answers
    current_question.answers.right_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable
  
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :added_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists

  validates :email, 
            format: { with: URI::MailTo::EMAIL_REGEXP }, 
            uniqueness: true

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def default_url_options
    { lang: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
  
  protected

  def after_sign_in_path_for(user)
    if user.admin?
      admin_tests_path
    else
      flash[:notice] = "Welcome #{current_user.name}"

      tests_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to cookies.delete(:requested_path) || root_path      
    else
      flash.now[:alert] = 'Если вы уже имеете учетную запись, введите ваш email и пароль'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    render :new
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    client = GistQuestionService.new(@test_passage.current_question)
    gist = client.call

    if client.success?

      current_user.gists.create!(question_id: @test_passage.current_question.id, 
        gist_url: gist.url)

      redirect_to @test_passage, notice: "#{t(".success")} #{view_context.link_to('Gist', gist.url)}"
    else
      redirect_to @test_passage, alert: t(".failure")
    end
  end


  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_message(type)
    if flash[type]
      content_tag :p, flash[type], class: "flash alert"
    end   
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Создать новый вопрос для теста - #{question.test.title}"
    else
      "Редактировать вопрос для теста - #{question.test.title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #D3D3D3;">
  <%= link_to "TestGuru", root_path, class: "navbar-brand" %>
  <%= link_to t('links.admin'), admin_tests_path, class: 'navbar-brand' %>
  <%= link_to t("links.gists"), admin_gists_path, class: 'navbar-brand' %> 
  <%= link_to t("links.tests"), admin_tests_path, class: 'navbar-brand' %>

  <div class="nav-admin user">
    Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>

    <%= csrf_meta_tags %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "admin/nav" %>
    <%= render "shared/flash" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    
    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, class: "alert #{key}", role: "alert" %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>
   <%= current_year %><br>
   Created by <%= link_to 'Manziuchka', github_url('Manziuchka', 'test-guru'), target: '_blank' %><br>
   TestGuru - приложение для прохождения тестов. <br>
   <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com/', target: '_blank' %>
  </p>

</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #D3D3D3;">
  <%= link_to "TestGuru", root_path, class: 'navbar-brand' %>

  <span class="navbar-text-center">
    <% if user_signed_in? %>
      <%= link_to t('links.admin'), admin_tests_path, class: 'navbar-brand' if current_user.admin?%>
    
      Welcome, <b><%= current_user.email %></b> Guru | 
        <%= link_to 'Log out', destroy_user_session_path,
                              method: :delete,
                              data: { confirm: t("links.confirmation") } %>
    <% else %>
        <%= link_to 'Login', new_user_session_path %> | 
        <%= link_to 'Signup', new_user_registration_path %>
    <% end %>
  </span>
</nav>