config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
     member do
       post :start
     end
   end

  resources :test_passages, only: %i[show update] do
    member do

      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASS_RATE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question


  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def question_number
    test.questions.ids.sort.index(current_question.id) + 1
  end

  def rate
    correct_questions / test.questions.count.to_f * 100
  end

  def passed?
    rate >= PASS_RATE
  end
   
  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    if answer_ids.present?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end    
  end

  def correct_answers
    current_question.answers.right_answers
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    client = GistQuestionService.new(@test_passage.current_question)
    gist = client.call

    if client.success?

      current_user.gists.create!(question_id: @test_passage.current_question.id, 
        gist_url: gist.url)

      redirect_to @test_passage, notice: "#{t(".success")} #{view_context.link_to('Gist', gist.url)}"
    else
      redirect_to @test_passage, alert: t(".failure")
    end
  end


  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t(".header", title: @test_passage.test.title) %></h1>

<p>
  <strong>Ваш результат:</strong> <%= @test_passage.correct_questions %> из <%= @test_passage.test.questions.count %>.
</p>

<% if @test_passage.passed?  %>
  <p style="color:#00ff00" >
    Тест пройден!
  </p>
<% else %>
  <p style="color:#ff0000">
    Тест не пройден!
  </p>
<% end %>

<p>
  <strong>Процент прохождения:</strong> <%= @test_passage.rate %>
</p>

<%= link_to 'Все тесты', tests_path %>

app/views/test_passages/show.html.erb
<h1>Прохождение теста <%= @test_passage.test.title %></h1>
<h2>Вопрос #<%= @test_passage.question_number %> из <%= @test_passage.test.questions.count %></h2>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden:
  false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next' %></p>
<% end %>