config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
     member do
       post :start
     end
   end

  resources :test_passages, only: %i[show update] do
    member do

      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_numbers_of_answers

  scope :right_answers, -> { where(correct: true) }

  private

  def validate_numbers_of_answers
    errors.add(:answers, "too much") if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[ new create]
  before_action :set_answer, only: %i[ show edit update destroy ]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end
  
  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: 'Вопрос успешно создан.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), notice: 'Вопрос успешно изменен.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

    def find_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %>
  <%= link_to "Просмотр", admin_answer_path(answer) %> |
	<%= link_to "Изменить", edit_admin_answer_path(answer) %> |
	<%= link_to "Удалить", admin_answer_path(answer),
                             method: :delete,
                             data:   { confirm: "Вы уверены?" } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :bodyt, "Ответ" %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct, "Правильный?"  %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Редактирование вопроса</h1>

<p> 
  <%= @answer.question.body%>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Просмотр', [:admin, @answer] %> |
<%= link_to 'Назад', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>Новый ответ</h1>

<p>
  <%= @question.body %>
</p>

<%= render "form" %>
<%= link_to 'Назад', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Вопрос</h1>

</p>
  <%= @answer.question.body %>
<p>

<p>
  <b>Ответ:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Верный ответ?</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Назад', admin_question_path(@answer.question) %>