config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
     member do
       post :start
     end
   end

  resources :test_passages, only: %i[show update] do
    member do

      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def index
    @questions = @test.questions
  end

  def show
    @question
  end

  def edit; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to [:admin, @question.test]
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Создать новый вопрос для теста - #{question.test.title}"
    else
      "Редактировать вопрос для теста - #{question.test.title}"
    end
  end
end

app/views/admin/questions/_form.html.erb
<h1><%= question_header(@question) %></h1>
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <% if @question.errors.present? %>
    <div>
      <h2>Errors detected:</h2>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>          
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
  <p>
    <%= form.label :body, "Текст вопроса" %><br>
    <%= form.text_area :body, rows: 7, cols: 60 %>
  </p>
  
  <%= form.submit %>
  </table><br>
<% end %>

app/views/admin/questions/edit.html.erb
<h1>Edit <%= @question.test.title %> Question</h1>

<%= render "form" %>
<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/index.html.erb
<h1>Вопросы:</h1>

<table border="1">
  <tr>
    <th>Id</th>
    <th>Текст вопроса</th>
    <th colspan=3>Действия</th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <th><%= question.id %></th>
      <th><%= question.body %></th>
      <td><%= link_to "Просмотр", admin_question_path(question) %></td>
	    <td><%= link_to "Изменить", edit_admin_question_path(question) %></td>
        <td><%= link_to 'Удалить', admin_question_path(question), 
              method: :delete,
              data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

<p>
   <%= link_to "Создать новый вопрос", new_admin_test_question_path(@test) %>
</p>

app/views/admin/questions/new.html.erb
<%= render "form" %>
<%= link_to 'Back', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1>Тест: <%= @question.test.title %></h1>

<%= @question.body %>

<h2>Ответы</h2>
<%= link_to 'Новый ответ', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<p>
	<%= link_to "Назад", admin_test_path(@question.test) %> |
	<%= link_to "Изменить", edit_admin_question_path(@question) %> |
	<%= link_to "Удалить", admin_question_path(@question),
                             method: :delete,
                             data:   { confirm: "Удалить вопрос?" } %>
</p>